### ISSUE TITLE
Add many XFCE4-Apps

### ISSUE THREAD

**Issue by Schmensch** [mpsq/arewewaylandyet#109]
Even though XFCE itelf isn't wayland-native yet, all apps I tested are. This includes:

- Thunar (file manager)
- XFCE4-Terminal (terminal emulator, it's in the name)
- Ristrotto (Image viewer)
- Xarchiver (Archive manager)

**Comment by mpsq** [comment]
Closing -- We XFCE is a desktop environment, once most of its apps are ready, we will add XFCE directly to the corresponding section.
