### ISSUE TITLE
Opera now runs on pure wayland

### ISSUE THREAD

**Issue by specious** [mpsq/arewewaylandyet#111]
As user gigol [mentioned](https://forums.opera.com/topic/49172/status-of-wayland-support-and-how-to-enable/6) on the Opera forums, it now runs on pure wayland if launched with:

```
opera --enable-features=UseOzonePlatform --ozone-platform=wayland
```

Running opera-deverloper 80.0.4170.0 on Arch Linux with [sway](https://swaywm.org/) I can confirm that it does indeed.

**Comment by gmarconi** [comment]
Submitting PR
