### ISSUE TITLE
Default Chromium support is at least 8 month away

### ISSUE THREAD

**Issue by merlinschumacher** [mpsq/arewewaylandyet#14]
I wouldn't consider that soon. Also there are more than 20 blocking bugs for working Wayland support. Additionally, we won't know when the much more popular Google Chrome will get native Wayland support.
The linked Phoronix article states that "They hope that in the second half of 2021 that Ozone will be the default on Linux". That is not very reliable and it might take even more time.

**Comment by mpsq** [comment]
I added a link to think issue.

**Comment by kriive** [comment]
Well, Chrome/ium has a Wayland enabled backend in dev and beta channels already!

**Comment by mpsq** [comment]
Yes, and that's super exciting. 
I think I will stick to Merlin suggestion for now, I think it is correct to not advertise too much something that is not available out of the box.
I will update the website as soon as Wayland backend is enabled on stable :).

**Comment by chaitunya** [comment]
The Wayland backend is now available on chromium stable. Just run this command:

    chromium --enable-features=UseOzonePlatform --ozone-platform=wayland

To enable it permanently, add this text `--enable-features=UseOzonePlatform --ozone-platform=wayland` to `.config/chromium-flags.conf`

**Comment by mpsq** [comment]
Thanks for letting me know, I will add Chromium to the list then!
