### ISSUE TITLE
Krita does not support Wayland

### ISSUE THREAD

**Issue by TheSunCat** [mpsq/arewewaylandyet#167]
Hi! I really appreciate this website as it has been an incredible resource in the journey of switching to Wayland. However, I was sad to find out that Krita does not actually support Wayland. If run with the `--platform wayland` switch, Krita shows the following warning and then quits:
![image](https://user-images.githubusercontent.com/44881120/210412073-3ac70d19-ba1b-4c16-8039-625e42d634dd.png)

**Comment by equirosa** [comment]
It **could** be removed. Just wanna verify that it's correct to assume we only list native wayland programs and not including ones that run through XWayland, right, @mpsq?

(Literally just thought of the distinction now, and want to confirm)

**Comment by Idesmi** [comment]
@mpsq Krita is still visible on the website.
