### ISSUE TITLE
rendering model shortcomings

### ISSUE THREAD

**Issue by matu3ba** [mpsq/arewewaylandyet#168]
Stolen from reddit https://www.reddit.com/r/linux/comments/wwsiaf/comment/ilosxsf/?utm_source=share&utm_medium=web2x&context=3 with phrasing slightly adjusted:

rendering model

How it currently works is that compositors throttle rendering by not sending callbacks to surface that are out of focus. The throttling can indefinitely stall that application's thread until it comes back into view. The problem is that clients have no way of knowing if they hidden or not. What ends up often happening is that certain render loops do clever hacks/workarounds to guess when the surface is hidden or not to avoid this stalling. There was a protocol proposal to fix this, but it got bikeshedded and probably will never be merged. Note that Wayland is literally the only windowing protocol that works like this and everywhere else it's trivial. What Wayland should have done was just send visibility events instead of callbacks and then encourage applications to not draw when the surface is not visible.

**Comment by matu3ba** [comment]
> This is not relevant to this repository

- 1. README says `I think so... This is an opinionated answer, if you disagree or if you think something is missing, I would love to hear about it, please open an issue or a pull request.`
- 2. You are very dismissive `stuff you read on social media`.
- 3. I would prefer a technical argument written in a public space rather than potentially incorrect private conversations.
- 4. There is nothing wrong about admitting shortcomings. After all, everything is a tradeoff.

**Comment by wiki-me** [comment]
> README says I think so... This is an opinionated answer, if you disagree or if you think something is missing, I would love to hear about it, please open an issue or a pull request.

Fair enough, i doubt this is what the repo owner is interested in but i will let him decide if to close the issue.

> You are very dismissive stuff you read on social media.

The wayland developers mentioned years ago to be careful about stuff that gets written in places like hacker news and lwn comments, Even thought my interest in wayland is pretty casual, i noticed people writing incorrect things, corrected them only to see them get written again and again , there is even a name for this phenomena (the [BS asymmetry principle](https://en.wikipedia.org/wiki/Brandolini%27s_law)). I am not saying social media is all bad but you should try to find better and more relaliabe sources.

> Where else would you clarify these from your point bogous statements?

Maybe the [wayland developers mailing list](https://lists.freedesktop.org/mailman/listinfo/wayland-devel) or the [wayland gitlab](https://gitlab.freedesktop.org/wayland) on freedesktop, The issue tracker of major implementations (wlroots/smithay/KDE) might also be appropriate.

But I think unless you plan to do something about these things you might want to skip it, The time and resources the linux desktop gets is already pretty limited.

Not saying this is not valid criticism but this sounds wrong.

**Comment by mpsq** [comment]
This seems to be (fair) criticism of some wayland design decisions. This is important feedback however arewewaylandyet.com is not the right place for this, it is mostly a website to help new wayland users to find replacement for their favourite tools or at least alternatives. IMO, the comment you quoted should be sent directly to the core wayland developers via mailing lists.
