### ISSUE TITLE
Add 'Displaying remote content' and 'Sharing display'

### ISSUE THREAD

**Issue by ClashTheBunny** [mpsq/arewewaylandyet#31]
It would be nice to add a list of vnc or remote display possibilities.  It comes up often on discussion sites like:
https://lobste.rs/s/pmqmzs/are_we_wayland_yet#c_fjzugv

At least waypipe: https://gitlab.freedesktop.org/mstoeckl/waypipe/-/blob/master/README.md

Arch's wiki has a few: https://wiki.archlinux.org/index.php/wayland#Remote_display

**Comment by mpsq** [comment]
We have the "Screenshot/screen capture & share tool" category already, but maybe it is not ideal.

We could:

- Rename this category to "Screenshot/screen capture" and remove `wayvnc` from the list
- Add a new "Remote display tool" category with `waypipe`, `wayvnc` and `gnome-remote-desktop`

What do you think?

**Comment by ClashTheBunny** [comment]
Since it regularly comes up, it would probably work to combat the common conception that remote is absent completely!

**Comment by myfreeweb** [comment]
> Add a new "Remote display tool" category with waypipe, wayvnc

These should be in different (sub)categories, waypipe is "application forwarding" or indeed "network transparency" as it is now. Ideally both of these terms, as well as the `ssh -X` magic term should be mentioned.

**Comment by mpsq** [comment]
@myfreeweb what do you think of:

- Network transparency: waypipe
- Screenshot/recording tool: grim/slurp, OBS (with a plugin), swappy, wf-recorder
- Remote control tool: gnome-remote-desktop, wayvnc

Would that address your comment?

**Comment by myfreeweb** [comment]
Yeah.. Well, I'm not sure about squashing screenshot and recording together, but whatever

**Comment by mpsq** [comment]
Ok, I will do:

- Network transparency: waypipe
- Remote control tool: gnome-remote-desktop, wayvnc
- Screen recording tool: OBS (with a plugin), wf-recorder
- Screenshot tool: grim/slurp, swappy

then, thanks.
