### ISSUE TITLE
Mention Electron Apps under Chromium Caveat

### ISSUE THREAD

**Issue by WingofaGriffin** [mpsq/arewewaylandyet#58]
Maybe this deserves turning Chromium into it's own subsection in the Nvidia style, though I think explicitly mentioning Electron based apps wouldn't be a bad idea (despite Electron's bad press it gets), as many apps people care about run on the platform, ie. Spotify, Discord, VSCode, Slack, Etcher, etc.

As mentioned in [this issue](https://github.com/electron/electron/issues/9056) the electron team is expecting compatibility once Chromium is enabled. I know this should be obvious for a lot of people, though full transparency and lack of assumptions are probably smart here, as the idea is to get people excited and confident about Wayland's viability over X. A large portion of the [most popular packages in the AUR](https://aur.archlinux.org/packages/) are Electron based, so the popularity is there.

**Comment by Half-Shot** [comment]
As per https://github.com/electron/electron/issues/10915, Electron v12 supports Wayland. However, GNOME does not render titlebars yet so it may be worth holding off until that is a thing: https://github.com/electron/electron/issues/27016

**Comment by WhyNotHugo** [comment]
Wayland support is there now, but downstream applications have to collaborate now.

Applications need to update to electron v12. For application that only provide binaries, they also need to make sure they build with wayland support enabled (since it's possible to build without it).

**Comment by mpsq** [comment]
As the last comment states, Electron now supports Wayland natively (with caveats). I will close this issue since I prefer to list apps individually rather than a "framework" itself.
