### ISSUE TITLE
Add lack of cooperation by Nvidia

### ISSUE THREAD

**Issue by mixedCase** [mpsq/arewewaylandyet#6]
One of the two largest discrete GPU vendors does not support GBM and EGLStreams has poor or no support on most compositors. Given that Nvidia users form the majority of the gaming and machine learning userbase, this should get a mention.

**Comment by mpsq** [comment]
That's fair enough, I will add a section about missing stuff then. Hopefully Nvidia support will be the only thing.

**Comment by mpsq** [comment]
Done
