### ISSUE TITLE
Add key remapper: Interception Tools 

### ISSUE THREAD

**Issue by aaronamk** [mpsq/arewewaylandyet#67]
[Interception Tools](https://gitlab.com/interception/linux/tools) is an xmodmap and xcape alternative (that works better IMO). Specifically, the "[dual function keys](https://gitlab.com/interception/linux/plugins/dual-function-keys)" official plugin is great.

**Comment by gmarconi** [comment]
@mpsq I opened a pr, so I guess we can close this one when the PR gets merged
