### ISSUE TITLE
Linux distros

### ISSUE THREAD

**Issue by Relected** [mpsq/arewewaylandyet#69]
You might add a list of linux distros that ships wayland by defaults (i.e Ubuntu 21.04, fedora, Manjaro sway, opensuse GNOME)

**Comment by Schmensch** [comment]
If an desktop supports Wayland, it'll most likely ship with wayland enabled by default. Almost all distros which ship Gnome 3 ship with Gnome Wayland. Only exception is KDE Plasma, right now only Fedora ships with the (still pretty buggy) wayland mode enabled by default.

**Comment by mpsq** [comment]
It is a good idea, I am not sure where to draw the line between distros though, should we list only distros with Wayland enabled by default? What about Archlinux / gentoo and others?

**Comment by Relected** [comment]
> It is a good idea, I am not sure where to draw the line between distros though, should we list only distros with Wayland enabled by default? What about Archlinux / gentoo and others?

You should only list distros that ship wayland by default, Arch, gentoo and void users **_Should_** already know what they are doing

**Comment by Tachi107** [comment]
And don't forget about Debian, they enabled it [by default in 2019](https://www.debian.org/releases/buster/amd64/release-notes/ch-whats-new.html#wayland-by-default-on-gnome)
