### ISSUE TITLE
Remove plugin mention from OBS-Studio

### ISSUE THREAD

**Issue by MGThePro** [mpsq/arewewaylandyet#71]
With wayland support now [fully merged](https://github.com/obsproject/obs-studio/pull/2484), it's not needed to install a plugin anymore

**Comment by deltragon** [comment]
I dont think the plugin mention can be removed yet - the merged PR was just for OBS itself to run on Wayland, not whether screen capturing works (if I understand correctly).
It seems that [this PR](https://github.com/obsproject/obs-studio/pull/3338) would enable that (it is also linked on the plugin's [readme](https://gitlab.gnome.org/feaneron/obs-xdg-portal)), but it is not merged yet.

**Comment by darkbasic** [comment]
#3338 is merged now.

**Comment by mpsq** [comment]
Waiting for OBS 27 to be released before removing the mention to the plugin.
