### ISSUE TITLE
Add terminator to list of terminal emualtors

### ISSUE THREAD

**Issue by baryluk** [mpsq/arewewaylandyet#75]
I use terminator under X11/Mate for years, and I just tried it under wayland, and it works, no extra options required.

https://terminator-gtk3.readthedocs.io/en/latest/

https://github.com/gnome-terminator/terminator

I used version 2.1.0 from Debian testing running under weston, but probably it works is a bit earlier versions.

**Comment by gmarconi** [comment]
@mpsq this one can be closed

**Comment by mpsq** [comment]
Thanks!
