### ISSUE TITLE
evince PDF reader

### ISSUE THREAD

**Issue by baryluk** [mpsq/arewewaylandyet#76]
That is quite obvious to people who, know but not obvious to people that don't know.

evince works under wayland.

Also atril - a MATE fork of GNOME 2 evince, should now work under wayland - https://github.com/mate-desktop/atril/pull/504  , the version 1.24 doesn't work, but but 1.26 should have this fixed.

**Comment by mcepl** [comment]
And it is not only PDF viewer: there are plugins, like evince-plugin-comicsdocument, evince-plugin-djvudocument, evince-plugin-dvidocument, evince-plugin-pdfdocument, evince-plugin-psdocument, evince-plugin-tiffdocument, evince-plugin-xpsdocument.

**Comment by nesper8** [comment]
Added
