### ISSUE TITLE
inkscape  a vector-based drawing program

### ISSUE THREAD

**Issue by baryluk** [mpsq/arewewaylandyet#78]
Well, `inkscape` 1.0.2 from Debian testing works.

Also, I think that is quite important - `gimp` doesn't work, and people should know about it.

**Comment by gmarconi** [comment]
opened a PR

**Comment by gmarconi** [comment]
Should we close this one as we don't have a gimp substitute yet?

**Comment by mpsq** [comment]
Yes, that sounds good to me. Thanks!
