### ISSUE TITLE
window / input automation - ydotool, wtype

### ISSUE THREAD

**Issue by baryluk** [mpsq/arewewaylandyet#79]
Under X11 I usually use xdotool or xdo.

Under wayland it looks there is `ydotool` ( https://github.com/ReimuNotMoe/ydotool  ) and `wtype` ( https://github.com/atx/wtype )  that provides some similarity and functionality.

However, I didn't actually have any success with `ydotool` or `wtype` under weston, they throw exception or complain about backend or about `virtual keyboard protocol` missing).

**Comment by mpsq** [comment]
Already mentioned, also, if users are running into issues they should report them upstream. Now closing.
