### ISSUE TITLE
The wdisplay community has splitted up

### ISSUE THREAD

**Issue by victorgveloso** [mpsq/arewewaylandyet#99]
Since https://github.com/cyclopsian/wdisplays repo has gone (available at the [internet archive](https://web.archive.org/web/20210204184506/https://github.com/cyclopsian/wdisplays)), people were looking for a new upstream repo to follow.
https://arewewaylandyet.com/ redirects to https://github.com/luispabon/wdisplays
However, https://aur.archlinux.org/packages/wdisplays-git/ relies on https://github.com/artizirk/wdisplays

Luispabon [added the following text](https://github.com/luispabon/wdisplays/commit/7f2eac0d2aa81b5f495da7950fd5a94683f7868e) to README.md

> ## Luis' Note
> 
> Looks like the [original repository](https://github.com/cyclopsian/wdisplays.git) has disappeared, so since GPL v3 allows I've created a fork of it. Not sure I want to maintain it but for now it won't hurt to have it here.

On the other hand, artizirk merged two patches (https://github.com/artizirk/wdisplays/commit/5198a9c94b40ff157c284df413be5402f1b75118 and https://github.com/artizirk/wdisplays/commit/cfc833984edf7d3033d09333968a97b82d6ef2cf) as mentioned [in the package's comment section on AUR](https://aur.archlinux.org/packages/wdisplays-git/)

>  arti commented on 2021-03-29 08:39	
> 
> Looks like upstream repo is gone. I pushed the latest commits with emersion patch here https://github.com/artizirk/wdisplays

How should we proceed?

**Comment by mpsq** [comment]
Thanks for reporting this, I will update the link.
